version: "3.9"

services:
  db:
    image: postgres:15.2
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    env_file: .env
    ports:
      - ${REDIS_PORT:-6379}:6379

  server:
    build: .
    command: poetry run glitch server
    env_file: .env
    ports:
      - ${SERVER_PORT:-5000}:5000
    depends_on:
      - db
      - redis

  client:
    build: .
    command: poetry run glitch bot
    env_file: .env
    depends_on:
      - db
      - redis
      - server

volumes:
  db_data:
