version: "3.9"

services:
  db:
    image: postgres:15.2
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis/redis-stack:latest
    ports:
      - ${REDIS_PORT:-6379}:6379

volumes:
  db_data:
